---
driver:
  name: dokken
  chef_version: 12

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      privileged: true
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: centos-7
    driver:
      privileged: true
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[test::sshd]
      - recipe[test::exectest]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
